### ISSUE TITLE
`CXX_STD = CXX11` causes CRAN note on devel

### ISSUE THREAD

**Issue by rorynolan** [RcppCore/RcppParallel#196] opened 2023-02-04 17:13 UTC
`CXX_STD = CXX11` causes a CRAN note. The current CRAN default is C++17 and it doesn't like you to specify an older version.
The easy fix is to change the docs 11 -> 17 but that too will probably be too old someday. Perhaps the docs could just say that at least C++11 is required for RcppParallel to work but not do anything in Makevars?
Up to you how to tackle this, just wanted to make sure you were aware.

**Comment by eddelbuettel** [comment] 2023-02-04 18:07
Duplicate of #194

**Comment by kevinushey** [comment] 2023-02-04 18:24
I think there are some places we need to update:

- The skeleton function, here: https://github.com/RcppCore/RcppParallel/blob/649340b18dbaf834859c07e8701f3ea7a0c650da/R/skeleton.R#L108-L130
- The documentation for the GitHub pages site here: https://github.com/RcppCore/RcppParallel/blob/16876a23f98866b9985bc657c90c678d6c533314/index.Rmd#L80-L96

I'll fix those up.

**Closed** 2023-02-04 18:26 UTC

**Comment by eddelbuettel** [comment] 2023-02-04 18:37
One thing I have been wondering, though, is whether or not we should set a `CXX_STD`.  "Way back when" we had to as the then-default compiler was insisting on C++98.  Now we have modern C++ by default, and adding this feels like adding a constraint.  Should we just leave it open?  (IIRC) R 4.0.0 turned on C++11,  R 4.1.0 turned to C++14, R 4.3.0 will turn on C++17.  Good enough?
