### ISSUE TITLE
unable to compile: lto-wrapper failed (openSuse, gcc 9.2.1)

### ISSUE THREAD

**Issue by dsteuer** [RcppCore/RcppParallel#105] opened 2020-02-23 21:37 UTC
Trying to install RcppParallel in openSUSE Tumbleweed. Some time ago that was possible, 
but that were older releases of openSUSE. 
Since a few weeks compilation fails:

install.packages("RcppParallel")
...
g++ -std=gnu++11 -shared -L/usr/lib64/R/lib -flto=auto -o RcppParallel.so init.o options.o -L/usr/lib64/R/lib -lR
lto-wrapper: fatal error: execvp: Datei oder Verzeichnis nicht gefunden
compilation terminated.
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make: *** [/usr/lib64/R/share/make/shlib.mk:6: RcppParallel.so] Fehler 1
ERROR: compilation failed for package ‘RcppParallel’

Any hints? How can I help to debug the situation?

I've read the old issues but those seem different.

Detlef

**Comment by eddelbuettel** [comment] 2020-02-23 22:00
Hi Detlef. I think someone else just brought the same issue but we had no solution -- RcppParallel / Intel TBB likely to _not_ bring in `-lto` so could the R build have changed?

**Comment by dsteuer** [comment] 2020-02-23 22:26
Hi Dirk! Hmm. As I'm the maintainer of R-base for Suse I don't think so.  The spec file has no fancy news at all. Did the R build itself change with 3.6.2? So far RcppParallel is the only package showing these symptoms. How could I find out what pulls in the -lto?

**Comment by eddelbuettel** [comment] 2020-02-23 22:32
It may be new-ish gcc-9 default. LTO requires 'all parts' to be visible at once for 'optimisation at link time' (ie across all routines).  There I a 'no' option, from memory `-fno-lto` or some such. _Maybe_ we have to inject that somewhere.

It is as far as we know not biting anywhere else...

**Comment by dsteuer** [comment] 2020-02-23 22:42
Ah, ok, that makes sense. Google tells me, Suse switches/has switched to -flto=auto as default. Is it possible to build RcppParallel with explicitly disabled -fno-lto? Can I inject it for my local build?

**Comment by eddelbuettel** [comment] 2020-02-23 22:55
I am fuzzy about that because it /may/ be in R's own Makeconf and I never know if we can locally override it in src/Makevars.  But it is worth a try.

**Comment by dsteuer** [comment] 2020-02-24 08:52
I found: 
> R CMD config --ldflags
-Wl,--export-dynamic -fopenmp -flto=auto -L/usr/lib64/R/lib -lR -lpcre -llzma -lbz2 -lz -lrt -ldl -lm -licuuc -licui18n

That is R is compiled with -flto=auto.

And --ldflags says "needed for linking against R frontend".

Bad thing is: I'm no compiler expert, so have no idea how strong that "needed" is or how to test.

I replaced -flto=auto with -fno-lto after configure in Makevars, but tbb itself is compiled with flto=auto anyway (and breaks therefore). It seems tbb is exposed to default  gcc beheaviour -flto=auto and that doesn't work. Changing the Makefile(s) for tbb is beyond what I can easily do.

(The big problem is, that quanteda depends on RcppParallel and that is badly needed.)

**Comment by eddelbuettel** [comment] 2020-02-24 13:00
That sounds pretty delicate indeed and shows the limits of changing it within the R stack :-/

**Comment by kevinushey** [comment] 2020-02-24 17:58
Can you post the full compilation output? In particular I want to see what is being set for `CXXFLAGS` etc. during compilation.

I'm not sure if I'll have time to take a look this week though :-/

**Comment by dsteuer** [comment] 2020-02-25 07:41
Of course (this is with hand-patched -fno-lto, the error in tbb is exactly the same with original Makvars and -flto=auto): 

> R CMD INSTALL RcppParallel_4.4.4-9000.tar.gz 
* installing to library ‘/home/steuer/R/x86_64-suse-linux-gnu-library/3.6’
* installing *source* package ‘RcppParallel’ ...
** using staged installation
** preparing to configure package 'RcppParallel' ...
*** executing 'R CMD config'

*** configured file: 'src/Makevars.in' => 'src/Makevars'
** finished configure for package 'RcppParallel'
** libs
mkdir -p ../inst/lib/; \
cd tbb/src; \
if [ -n "" ]; then \
   CONLY="gcc -I/usr/local/include" CPLUS="g++ -I/usr/local/include" CXXFLAGS="-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -fno-lto -DTBB_NO_LEGACY=1" PIC_KEY="-fpic" WARNING_SUPPRESS="" make -e -s stdver=c++0x compiler=clang tbb_release tbbmalloc_release tbb_build_prefix=lib; \
elif [ -n "gcc" ]; then \
   CONLY="gcc -I/usr/local/include" CPLUS="g++ -I/usr/local/include" CXXFLAGS="-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -fno-lto -DTBB_NO_LEGACY=1" PIC_KEY="-fpic" WARNING_SUPPRESS="" make -e -s stdver=c++0x compiler=gcc tbb_release tbbmalloc_release tbb_build_prefix=lib; \
else \
   CONLY="gcc -I/usr/local/include" CPLUS="g++ -I/usr/local/include" CXXFLAGS="-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -fno-lto -DTBB_NO_LEGACY=1" PIC_KEY="-fpic" WARNING_SUPPRESS="" make -e -s stdver=c++0x tbb_release tbbmalloc_release tbb_build_prefix=lib; \
fi; \
cd ../..; \
cp tbb/build/lib_release/libtbb*.* ../inst/lib/
Created ../build/lib_release directory
../../build/Makefile.tbb:32: CONFIG: cfg=release arch=intel64 compiler=gcc target=linux runtime=cc9_libc2.31_kernel5.5.4
../../src/tbbmalloc/proxy.cpp:212:7: warning: ‘void* __libc_valloc(size_t)’ specifies less restrictive attributes than its target ‘void* valloc(size_t)’: alloc_size’, ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  212 | void *__libc_valloc(size_t size) __attribute__ ((alias ("valloc")));
      |       ^~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:143:14: note: ‘void* __libc_valloc(size_t)’ target declared here
  143 | void *PREFIX(valloc)(ZONE_ARG size_t size) __THROW
      |              ^~~~~~
../../src/tbbmalloc/proxy.cpp:78:22: note: in definition of macro ‘PREFIX’
   78 | #define PREFIX(name) name
      |                      ^~~~
../../src/tbbmalloc/proxy.cpp:211:7: warning: ‘void* __libc_pvalloc(size_t)’ specifies less restrictive attributes than its target ‘void* pvalloc(size_t)’: ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  211 | void *__libc_pvalloc(size_t size) __attribute__ ((alias ("pvalloc")));
      |       ^~~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:173:7: note: ‘void* __libc_pvalloc(size_t)’ target declared here
  173 | void *pvalloc(size_t size) __THROW
      |       ^~~~~~~
../../src/tbbmalloc/proxy.cpp:210:7: warning: ‘void* __libc_memalign(size_t, size_t)’ specifies less restrictive attributes than its target ‘void* memalign(size_t, size_t)’: ‘alloc_size’, ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  210 | void *__libc_memalign(size_t alignment, size_t size) __attribute__ ((alias ("memalign")));
      |       ^~~~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:137:14: note: ‘void* __libc_memalign(size_t, size_t)’ target declared here
  137 | void *PREFIX(memalign)(ZONE_ARG size_t alignment, size_t size) __THROW
      |              ^~~~~~~~
../../src/tbbmalloc/proxy.cpp:78:22: note: in definition of macro ‘PREFIX’
   78 | #define PREFIX(name) name
      |                      ^~~~
../../src/tbbmalloc/proxy.cpp:209:7: warning: ‘void* __libc_calloc(size_t, size_t)’ specifies less restrictive attributes than its target ‘void* calloc(size_t, size_t)’: ‘alloc_size’, ‘leaf’, ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  209 | void *__libc_calloc(size_t num, size_t size) __attribute__ ((alias ("calloc")));
      |       ^~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:117:14: note: ‘void* __libc_calloc(size_t, size_t)’ target declared here
  117 | void *PREFIX(calloc)(ZONE_ARG size_t num, size_t size) __THROW
      |              ^~~~~~
../../src/tbbmalloc/proxy.cpp:78:22: note: in definition of macro ‘PREFIX’
   78 | #define PREFIX(name) name
      |                      ^~~~
../../src/tbbmalloc/proxy.cpp:208:7: warning: ‘void* __libc_malloc(size_t)’ specifies less restrictive attributes than its target ‘void* malloc(size_t)’: alloc_size’, ‘leaf’, ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  208 | void *__libc_malloc(size_t size) __attribute__ ((alias ("malloc")));
      |       ^~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:112:14: note: ‘void* __libc_malloc(size_t)’ target declared here
  112 | void *PREFIX(malloc)(ZONE_ARG size_t size) __THROW
      |              ^~~~~~
../../src/tbbmalloc/proxy.cpp:78:22: note: in definition of macro ‘PREFIX’
   78 | #define PREFIX(name) name
      |                      ^~~~
../../src/tbbmalloc/proxy.cpp:61:18: warning: ‘void* __TBB_malloc_proxy(size_t)’ specifies less restrictive attributes than its target ‘void* malloc(size_t)’: ‘alloc_size’, ‘leaf’, ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
   61 | extern "C" void *__TBB_malloc_proxy(size_t) __attribute__ ((alias ("malloc")));
      |                  ^~~~~~~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:112:14: note: ‘void* __TBB_malloc_proxy(size_t)’ target declared here
  112 | void *PREFIX(malloc)(ZONE_ARG size_t size) __THROW
      |              ^~~~~~
../../src/tbbmalloc/proxy.cpp:78:22: note: in definition of macro ‘PREFIX’
   78 | #define PREFIX(name) name
      |                      ^~~~
g++ -std=gnu++11 -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include -std=gnu++11 -I../inst/include/ -DRCPP_PARALLEL_USE_TBB=1 -fpic  -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto  -c init.cpp -o init.o
g++ -std=gnu++11 -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include -std=gnu++11 -I../inst/include/ -DRCPP_PARALLEL_USE_TBB=1 -fpic  -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto  -c options.cpp -o options.o
g++ -std=gnu++11 -shared -L/usr/lib64/R/lib -flto=auto -o RcppParallel.so init.o options.o -L/usr/lib64/R/lib -lR
lto-wrapper: fatal error: execvp: Datei oder Verzeichnis nicht gefunden
compilation terminated.
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make: *** [/usr/lib64/R/share/make/shlib.mk:6: RcppParallel.so] Fehler 1
ERROR: compilation failed for package ‘RcppParallel’
* removing ‘/home/steuer/R/x86_64-suse-linux-gnu-library/3.6/RcppParallel’

**Comment by dsteuer** [comment] 2020-04-24 14:58
Just to give it a bump. Version 5.0.0 has the same issue. No idea anyone?

**Comment by kevinushey** [comment] 2020-04-24 19:04
Does OpenSUSE distribute a standalone copy of libtbb? If so, how is that compiled? (I wonder if we need to do extra work to replicate those flags when RcppParallel's own bundled TBB is compiled)

Alternatively, we might need to either update the bundled version of TBB (or just allow for users to link to and use the system TBB).

**Comment by dsteuer** [comment] 2020-04-26 12:06
Am Fri, 24 Apr 2020 12:04:23 -0700
schrieb Kevin Ushey <notifications@github.com>:

> Does OpenSUSE distribute a standalone copy of libtbb?

Yes.
They have a libtbb2 2020.2

> If so, how is
> that compiled? (I wonder if we need to do extra work to replicate
> those flags when RcppParallel's own bundled TBB is compiled)
>

How can I find out, how it is compiled?
This is the place, where they build it:
https://build.opensuse.org/package/show/openSUSE:Factory/tbb

> Alternatively, we might need to either update the bundled version of
> TBB (or just allow for users to link to and use the system TBB).
>

The last one would be perfect, I guess.

Detlef

**Comment by robby81** [comment] 2020-04-27 11:42
cd oneTBB-2020.2
[   67s] + make 'OPTFLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g' -j4 tbb_build_prefix=obj

**Comment by robby81** [comment] 2020-04-27 11:43
in opensuse it seems to be compiled with -flto=auto
see above comment

**Comment by gsgxnet** [comment] 2020-05-01 21:38
Same issue here, openSUSE Tumbleweed, R upgraded to 4.0.0 (problem existed before as well) 
Error message a bit different: 
`lto-wrapper: fatal error: execvp: No such file or directory`

in detail: 
```
Created ../build/lib_release directory
../../build/Makefile.tbb:32: CONFIG: cfg=release arch=intel64 compiler=gcc target=linux runtime=cc9_libc2.31_kernel5.6.6
../../src/tbbmalloc/proxy.cpp:212:7: warning: ‘void* __libc_valloc(size_t)’ specifies less restrictive attributes than its target ‘void* valloc(size_t)’: ‘alloc_size’, ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  212 | void *__libc_valloc(size_t size) __attribute__ ((alias ("valloc")));
      |       ^~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:143:14: note: ‘void* __libc_valloc(size_t)’ target declared here
  143 | void *PREFIX(valloc)(ZONE_ARG size_t size) __THROW
      |              ^~~~~~
../../src/tbbmalloc/proxy.cpp:78:22: note: in definition of macro ‘PREFIX’
   78 | #define PREFIX(name) name
      |                      ^~~~
../../src/tbbmalloc/proxy.cpp:211:7: warning: ‘void* __libc_pvalloc(size_t)’ specifies less restrictive attributes than its target ‘void* pvalloc(size_t)’: ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  211 | void *__libc_pvalloc(size_t size) __attribute__ ((alias ("pvalloc")));
      |       ^~~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:173:7: note: ‘void* __libc_pvalloc(size_t)’ target declared here
  173 | void *pvalloc(size_t size) __THROW
      |       ^~~~~~~
../../src/tbbmalloc/proxy.cpp:210:7: warning: ‘void* __libc_memalign(size_t, size_t)’ specifies less restrictive attributes than its target ‘void* memalign(size_t, size_t)’: ‘alloc_size’, ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  210 | void *__libc_memalign(size_t alignment, size_t size) __attribute__ ((alias ("memalign")));
      |       ^~~~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:137:14: note: ‘void* __libc_memalign(size_t, size_t)’ target declared here
  137 | void *PREFIX(memalign)(ZONE_ARG size_t alignment, size_t size) __THROW
      |              ^~~~~~~~
../../src/tbbmalloc/proxy.cpp:78:22: note: in definition of macro ‘PREFIX’
   78 | #define PREFIX(name) name
      |                      ^~~~
../../src/tbbmalloc/proxy.cpp:209:7: warning: ‘void* __libc_calloc(size_t, size_t)’ specifies less restrictive attributes than its target ‘void* calloc(size_t, size_t)’: ‘alloc_size’, ‘leaf’, ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  209 | void *__libc_calloc(size_t num, size_t size) __attribute__ ((alias ("calloc")));
      |       ^~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:117:14: note: ‘void* __libc_calloc(size_t, size_t)’ target declared here
  117 | void *PREFIX(calloc)(ZONE_ARG size_t num, size_t size) __THROW
      |              ^~~~~~
../../src/tbbmalloc/proxy.cpp:78:22: note: in definition of macro ‘PREFIX’
   78 | #define PREFIX(name) name
      |                      ^~~~
../../src/tbbmalloc/proxy.cpp:208:7: warning: ‘void* __libc_malloc(size_t)’ specifies less restrictive attributes than its target ‘void* malloc(size_t)’: ‘alloc_size’, ‘leaf’, ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  208 | void *__libc_malloc(size_t size) __attribute__ ((alias ("malloc")));
      |       ^~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:112:14: note: ‘void* __libc_malloc(size_t)’ target declared here
  112 | void *PREFIX(malloc)(ZONE_ARG size_t size) __THROW
      |              ^~~~~~
../../src/tbbmalloc/proxy.cpp:78:22: note: in definition of macro ‘PREFIX’
   78 | #define PREFIX(name) name
      |                      ^~~~
../../src/tbbmalloc/proxy.cpp:61:18: warning: ‘void* __TBB_malloc_proxy(size_t)’ specifies less restrictive attributes than its target ‘void* malloc(size_t)’: ‘alloc_size’, ‘leaf’, ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
   61 | extern "C" void *__TBB_malloc_proxy(size_t) __attribute__ ((alias ("malloc")));
      |                  ^~~~~~~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:112:14: note: ‘void* __TBB_malloc_proxy(size_t)’ target declared here
  112 | void *PREFIX(malloc)(ZONE_ARG size_t size) __THROW
      |              ^~~~~~
../../src/tbbmalloc/proxy.cpp:78:22: note: in definition of macro ‘PREFIX’
   78 | #define PREFIX(name) name
      |                      ^~~~
g++ -std=gnu++11 -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include  -std=gnu++11 -I../inst/include/ -DRCPP_PARALLEL_USE_TBB=1 -fpic  -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g  -c init.cpp -o init.o
g++ -std=gnu++11 -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include  -std=gnu++11 -I../inst/include/ -DRCPP_PARALLEL_USE_TBB=1 -fpic  -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g  -c options.cpp -o options.o
g++ -std=gnu++11 -shared -L/usr/lib64/R/lib -flto=auto -o RcppParallel.so init.o options.o -L/usr/lib64/R/lib -lR
lto-wrapper: fatal error: execvp: No such file or directory
compilation terminated.
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make: *** [/usr/lib64/R/share/make/shlib.mk:6: RcppParallel.so] Error 1
ERROR: compilation failed for package ‘RcppParallel’
* removing ‘/usr/lib64/R/library/RcppParallel’

The downloaded source packages are in
        ‘/tmp/Rtmp7CZSEj/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("RcppParallel", Ncpus = 4) :
  installation of package ‘RcppParallel’ had non-zero exit status
```

`markovchain` depends on `RcppParallel` so install fails there as well. Did not check for further dependencies. I had hoped to find a way to use gcc8 which is installed here as well, but I do not know enough about configurations to get it going. 
`update-alternatives --config gcc` is not an option: 
`update-alternatives: error: no alternatives for gcc`

What else might help?

**Comment by dsteuer** [comment] 2020-05-02 15:04
I asked on the opensuse packaging list. they suppose to use their tbb. fair enough, but I was unable to modify the build process in such a way, that a system tbb would be used. Any hints how to do that?

**Comment by robby81** [comment] 2020-05-03 20:09
I need to use flowCore work my daily work which also depends on RcppParallel. Bad thing now with the switch to R 4.0 which need all packages to rebuilt

**Comment by gsgxnet** [comment] 2020-05-03 22:41
yes same here, with the upgrade to 4.0.0 which came automatically with my current Tumbleweed repo setup I was forced to rebuild/reinstall all packages for it. And now there is not a fallback to the former 4.x RcppParallel version which was still there under 3.6.3. It continiued to work when 5.0 upgrades failed, if I remember right. May be I could do a forced reinstall of some 4.x Rcpp to try out, but I never did that before, so it would be a 2 layer trial-and-error, from which I prefer  to refrain from at this moment.

**Comment by dsteuer** [comment] 2020-05-04 08:03
Am Sun, 03 May 2020 15:41:15 -0700
schrieb gsgxnet <notifications@github.com>:

> yes same here, with the upgrade to 4.0.0 which came automatically
> with my current Tumbleweed repo setup I was forced to
> rebuild/reinstall all packages for it. And now there is not a
> fallback to the former 4.x RcppParallel version which was still there
> under 3.6.3. It continiued to work when 5.0 upgrades failed, if I
> remember right. May be I could do a forced reinstall of some 4.x Rcpp
> to try out, but I never did that before, so it would be a 2 layer
> trial-and-error, from which I prefer  to refrain from at this moment.
>

It would not help to reinstall 3.6.3 or try RcppParallel 4.x.
RcppParallel stopped building
long ago, probably when Tumbleweed switched to -flto-auto. But I'm not
even sure about the exact moment when it started to fail. The existing
binaries shadowed the failure for some time.

We need some idea to get it working again ....

Detlef

>

**Comment by gsgxnet** [comment] 2020-05-04 18:09
Trial of a workaround:

Upgraded R to 4.0.0 on my other system which run LEAP 15.1, not TW.
Installed `RcppParallel 5.0.0` there. 
Created a `.tar.gz` of the RcppParallel folder which resides in that systems user R library loc.
Copied and extracted that to my TW user R lib. 
At least I can load the RcppParallel lib now. So I have a fall back binary for the foreseeable future, if that binary is compatible enough with my TW libs. Any hints how to test it? 
Generally I assume TW is backward compatible with LEAP 15.x, but it might depend on needed system libs by the foreign binary.

If somebody wants to try my binary I would upload/sent/... it.

Still only a possible workaround, not a solution, but I have to clue how to come to a solution.

**Comment by robby81** [comment] 2020-05-04 21:23
I would be willing to try it. I really need to have flowCore from Bioconductor back this week :-(.

**Comment by gsgxnet** [comment] 2020-05-05 00:14
see https://github.com/gsgxnet/ztmp/blob/master/RcppParallel.tar.gz - only for testing

**Comment by robby81** [comment] 2020-05-05 06:48
when I have it correct, flowCore depends on cytolib which depends on RcppParallel. 
Thanks for the built, at least I can compile all packages I need now, will test whether they work properly later on. However, a real solution is still warranted.

**Comment by gsgxnet** [comment] 2020-05-05 10:50
I think we have to pinpoint the root cause for these problems. 
Ubuntu 20.04 comes with similar new versions of TBB (not sure) and gcc/g++ (9.3) like TW. If RcppParallel is okay there it might be more of a TW issue.

https://rtask.thinkr.fr/installation-of-r-4-0-on-ubuntu-20-04-lts-and-tips-for-spatial-packages/

**Comment by dsteuer** [comment] 2020-05-05 12:20
Hi!

Could you send me a complete build log for the leap install?
Will try to spot any difference.

Also which version of gcc? g++?

This is really painful atm.

Glad that works as a workaround.

Detlef

Am Mon, 04 May 2020 11:09:34 -0700
schrieb gsgxnet <notifications@github.com>:

> Trial of a workaround:
>
> Upgraded R to 4.0.0 on my other system which run LEAP 15.1, not TW.
> Installed `RcppParallel 5.0.0` there.
> Created a `.tar.gz` of the RcppParallel folder which resides in that
> systems user R library loc. Copied and extracted that to my TW user R
> lib. At least I can load the RcppParallel lib now. So I have a fall
> back binary for the foreseeable future, if that binary is compatible
> enough with my TW libs. Any hints how to test it? Generally I assume
> TW is backward compatible with LEAP 15.x, but it might depend on
> needed system libs by the foreign binary.
>
> If somebody wants to try my binary I would upload/sent/... it.
>
> Still only a possible workaround, not a solution, but I have to clue
> how to come to a solution.
>

**Comment by dsteuer** [comment] 2020-05-05 12:40
Another data point: I tried the work of debian to use the system tbb.
https://salsa.debian.org/r-pkg-team/r-cran-rcppparallel/-/blob/master/debian/patches/use_debian_packaged_libtbb.patch

Same error:
use system tbb
g++ -std=gnu++11 -I"/usr/lib64/R/include" -DNDEBUG -I../inst/include  -I/usr/local/include  -std=gnu++11 -DRCPP_PARALLEL_USE_TBB=1 -fpic  -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto  -c init.cpp -o init.o
g++ -std=gnu++11 -I"/usr/lib64/R/include" -DNDEBUG -I../inst/include  -I/usr/local/include  -std=gnu++11 -DRCPP_PARALLEL_USE_TBB=1 -fpic  -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto  -c options.cpp -o options.o
g++ -std=gnu++11 -shared -L/usr/lib64/R/lib -flto=auto -o RcppParallel.so init.o options.o -ltbb -L/usr/lib64/R/lib -lR
lto-wrapper: fatal error: execvp: No such file or directory
compilation terminated.
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make: *** [/usr/lib64/R/share/make/shlib.mk:6: RcppParallel.so] Fehler 1
ERROR: compilation failed for package ‘RcppParallel’

So it is *not* the way the package tries to build tbb, but the linking step fails anyway. 
Any new idea?

**Comment by kevinushey** [comment] 2020-05-05 16:56
I'm going to try and fix this today.

**Comment by kevinushey** [comment] 2020-05-05 17:11
I've pushed a fix to master that at least works around the issue for me. Can you check whether installation works with:

```
remotes::install_github("RcppCore/RcppParallel")
```

Thanks!

**Comment by dsteuer** [comment] 2020-05-05 19:26
Am Tue, 05 May 2020 10:11:46 -0700
schrieb Kevin Ushey <notifications@github.com>:

> I've pushed a fix to master that at least works around the issue for
> me. Can you check whether installation works with:
>
> ```
> remotes::install_github("RcppCore/RcppParallel")
> ```
>
> Thanks!
>


Someone <matz@suse.de> from Suse in the evening sent the following
elegant solution. I just came home and found both solutions in my inbox!

(I can confirm, yours is working, too)

To get RcppParallel compiling, it is enough to change the line 38
of src/Makevars.in

from
MAKE += -e -s
to
MAKEFLAGS += -e +s

Here is his, Matz', complete explanation:
---
> The only possible problem we could find, was the usage of
> -flto-auto for the included tbb library.

(see below for the solution)

You can verify if this is the case by following
https://en.opensuse.org/openSUSE:LTO for disabling LTO for this one
package. (Add '%define _lto_cflags %{nil}' in your spec file).  Note
that if this helps it's really only a work-around for something that
should be fixed correctly.

... hmm, looking at the build log (note that it also
fails on SLE-12, for package policy reasons), it has:

[  225s] g++ -std=gnu++11 -shared -L/usr/lib64/R/lib -flto=auto -o
RcppParallel.so init.o options.o -L/usr/lib64/R/lib -lR
[  225s] lto-wrapper: fatal error: execvp: No such file or directory
[  225s] compilation terminated.
[  225s]
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld:
error: lto-wrapper failed [  225s] collect2: error: ld returned 1 exit
status

which is really strange, it's not an usual problem with LTO itself, but
rather that it can't call a helper that's needed for the linking
process, which should come from the gcc9 package itself.

Digging deeper... The message is misleading, the parallel LTO
compilation internally uses make and some temporary makefiles, and the
lto-wrapper tries to call make like so:

20182 execve("/usr/bin/make -e -s", ["make -e -s", "-f",
"/tmp/ccSBBfs4.mk", "-j8", "all"], 0x7ffe9d9873c0 /* 98 vars */) = -1
ENOENT (No such file or directory)

Note that the executable it's trying to call is 'make -e -s'.  This
comes from the setting of 'MAKE' in src/Makevars:

  ...
  MAKE += -e -s
  MAKE_CMD =                                  \
    CONLY="$(CC) $(CPPFLAGS)"                   \
  ...

This is an unusual use of the $(MAKE) variable for makefiles.  The more
traditionl one to change setting for the current invocation of make is
to use MAKEFLAGS (like further up is already done for Windows and -j1).
 So changing this to

  MAKEFLAGS += -e -s

solves the problem you have.

This _does_ point to a problem in GCC, though, because the above usage
of MAKE to smuggle in command line args for make does work in general.
So lto-wrapper needs to do word splitting on spaces for that
environment variable, when it uses it.  (CCing Martin for this)

---

I think this solution is just simpler and more general.

Anyway thanks a lot for taking care!

Detlef

**Comment by dsteuer** [comment] 2020-05-05 19:29
Am Tue, 5 May 2020 21:26:40 +0200
schrieb Detlef Steuer <detlef.steuer@gmx.de>:

> from
> MAKE += -e -s
> to
> MAKEFLAGS += -e +s

MAKEFLAGS += -e -s

sorry, I better should have copy'n'pasted.

Detlef

**Comment by kevinushey** [comment] 2020-05-05 19:32
Thanks! Updating MAKEFLAGS rather than MAKE seems like a better solution -- I'll play with that.

**Comment by kevinushey** [comment] 2020-05-05 19:45
Looks like it does indeed help -- I've made that change on master. I'll try to submit to CRAN soon as well.

**Comment by gsgxnet** [comment] 2020-05-05 21:05
For me the call:
`g++ -std=gnu++11 -shared -L/usr/lib64/R/lib -flto=auto -o RcppParallel.so init.o options.o -ltbb -L/usr/lib64/R/lib -lR` is the problem. There the linking with link-time-optimisation is prepared / done. According to `g++ --help` `-shared` stands for ` Create a shared library.` ( I am not sure whether this is new or has already been stated before) 

Do the TW and the Leap RcppParallel come with the same `Makefile`? 

When I have again access to the LEAP system I will reinstall `RcppParallel` and capture the install log.

**Comment by dsteuer** [comment] 2020-05-05 21:26
Just in case you missed the good news: issue is solved :-)
and patch already in master!

Detlef

Am Tue, 05 May 2020 14:05:31 -0700
schrieb gsgxnet <notifications@github.com>:

> For me the call:
> `g++ -std=gnu++11 -shared -L/usr/lib64/R/lib -flto=auto -o
> RcppParallel.so init.o options.o -ltbb -L/usr/lib64/R/lib -lR` is the
> problem. There the linking with link-time-optimisation is prepared /
> done. According to `g++ --help` `-shared` stands for ` Create a
> shared library.` ( I am not sure whether this is new or has already
> been stated before)
>
> Do the TW and the Leap RcppParallel come with the same `Makefile`?
>
> When I have again access to the LEAP system I will reinstall
> `RcppParallel` and capture the install log.
>

**Comment by gsgxnet** [comment] 2020-05-05 21:30
Yeah, got it. 
So the next package update will bring it to me, I assume. 

Great, thanks for all the effort!

**Comment by kevinushey** [comment] 2020-05-08 17:18
There is a new version of RcppParallel on CRAN with this fix -- hopefully all should be well now. Please feel free to re-open if you're still having trouble. Thanks!

**Closed by kevinushey** 2020-05-08 17:18 UTC

**Comment by gsgxnet** [comment] 2020-05-09 13:00
compiled and installed fine here as RcppParallel 5.0.1 with my typical `update.packages()`. 
Great, Thanks.
