### ISSUE TITLE
Building from source on windows fails, cannot find -ltbb - ltbbmalloc

### ISSUE THREAD

**Issue by cdriveraus** [RcppCore/RcppParallel#118] opened 2020-06-02 15:47 UTC
Just as per the subject. Maybe this is expected? If not, I expect this relates to (causes) the issues here also:
https://discourse.mc-stan.org/t/problems-linking-to-tbb-with-latest-stanheaders/15562/2

error from windows x64 source install of CRAN RcppParallel 5.01:

> * installing *source* package 'RcppParallel' ...
> ** package 'RcppParallel' successfully unpacked and MD5 sums checked
> ** using staged installation
> ** preparing to configure package 'RcppParallel' ...
> *** executing 'R CMD config'
> *** executing 'R CMD config'
> *** configured file: 'src/Makevars.in' => 'src/Makevars'
> ** finished configure for package 'RcppParallel'
> ** libs
> make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
> Created ../build/lib_release directory
> ../../build/Makefile.tbb:32: CONFIG: cfg=release arch=intel64 compiler=gcc target=windows runtime=mingw
> C:/rtools40/mingw64/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o RcppParallel.dll tmp.def init.o options.o -L../inst/lib/x64/ -ltbb -ltbbmalloc -LC:/PROGRA~1/R/R-4.0.0/bin/x64 -lR
> C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ltbb
> C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ltbbmalloc
> collect2.exe: error: ld returned 1 exit status

**Comment by kevinushey** [comment] 2020-06-08 21:13
It works on my Windows VM, and it builds on CRAN, so most likely there is something specific to your environment preventing compilation.

It may also be helpful to know exactly what command(s) you're using to install RcppParallel.

```
> install.packages("RcppParallel", type = "source")
Installing package into 'C:/Users/kevinushey/r/win-library/4.0'
(as 'lib' is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/RcppParallel_5.0.1.tar.gz'
 length 1265516 bytes (1.2 MB)
downloaded 1.2 MB

* installing *source* package 'RcppParallel' ...
** package 'RcppParallel' successfully unpacked and MD5 sums checked
** using staged installation
** preparing to configure package 'RcppParallel' ...
*** executing 'R CMD config'
*** executing 'R CMD config'
*** configured file: 'src/Makevars.in' => 'src/Makevars'
** finished configure for package 'RcppParallel'
** libs

*** arch - i386
Created ../build/lib_release directory
../../build/Makefile.tbb:32: CONFIG: cfg=release arch=ia32 compiler=gcc target=windows runtime=mingw
Microsoft Windows [Version 10.0.18363.836]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\tmp\RtmpgDBQYc\R.INSTALL13882ca3df7\RcppParallel\src-i386\tbb\build\lib_release>task.o: duplicate section `.rdata$_ZTIN3tbb4taskE[__ZTIN3tbb4taskE]' has different size
arena.o: duplicate section `.rdata$_ZTIN3tbb4taskE[__ZTIN3tbb4taskE]' has different size
scheduler.o: duplicate section `.rdata$_ZTIN3tbb4taskE[__ZTIN3tbb4taskE]' has different size
C:/rtools40/mingw32/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o RcppParallel.dll tmp.def init.o options.o -L../inst/lib/i386/ -ltbb -ltbbmalloc -LC:/R/R-40~1.0/bin/i386 -lR
installing to C:/Users/kevinushey/r/win-library/4.0/00LOCK-RcppParallel/00new/RcppParallel/libs/i386

*** arch - x64
Created ../build/lib_release directory
../../build/Makefile.tbb:32: CONFIG: cfg=release arch=intel64 compiler=gcc target=windows runtime=mingw
Microsoft Windows [Version 10.0.18363.836]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\tmp\RtmpgDBQYc\R.INSTALL13882ca3df7\RcppParallel\src-x64\tbb\build\lib_release>task.o: duplicate section `.rdata$_ZTIN3tbb4taskE[_ZTIN3tbb4taskE]' has different size
arena.o: duplicate section `.rdata$_ZTIN3tbb4taskE[_ZTIN3tbb4taskE]' has different size
scheduler.o: duplicate section `.rdata$_ZTIN3tbb4taskE[_ZTIN3tbb4taskE]' has different size
C:/rtools40/mingw64/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o RcppParallel.dll tmp.def init.o options.o -L../inst/lib/x64/ -ltbb -ltbbmalloc -LC:/R/R-40~1.0/bin/x64 -lR
installing to C:/Users/kevinushey/r/win-library/4.0/00LOCK-RcppParallel/00new/RcppParallel/libs/x64
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'RcppParallel'
    finding HTML links ... done
    RcppParallel-package                    html  
    RcppParallel.package.skeleton           html  
    RcppParallelFlags                       html  
    setThreadOptions                        html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (RcppParallel)

The downloaded source packages are in
	'C:\tmp\RtmpcNdYxq\downloaded_packages'
```

**Comment by hansvancalster** [comment] 2020-07-16 18:53
@kevinushey 
I seem to have the same issue, when I try to install from source it fails:

````
> install.packages("RcppParallel", type = "source")
Installing package into ‘C:/R/Library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/RcppParallel_5.0.2.tar.gz'
Content type 'application/x-gzip' length 1341240 bytes (1.3 MB)
downloaded 1.3 MB

Warning message:
In options(papersize = "a4", tab.width = 2, width = 80, help_type = "html",  :
  'options(stringsAsFactors = TRUE)' is deprecated and will be disabled
* installing *source* package 'RcppParallel' ...
** package 'RcppParallel' successfully unpacked and MD5 sums checked
** using staged installation
Warning message:
In options(papersize = "a4", tab.width = 2, width = 80, help_type = "html",  :
  'options(stringsAsFactors = TRUE)' is deprecated and will be disabled
** preparing to configure package 'RcppParallel' ...
*** configured file: 'src/Makevars.in' => 'src/Makevars'
** finished configure for package 'RcppParallel'
** libs

*** arch - i386
Created ../build/lib_release directory
../../build/Makefile.tbb:32: CONFIG: cfg=release arch=ia32 compiler=gcc target=windows runtime=mingw
g++.exe: error: unrecognized command line option '-flifetime-dse=1'
make[2]: *** [../../build/common_rules.inc:119: concurrent_hash_map.o] Error 1
make[1]: *** [Makefile:104: tbb_release] Error 2
cp: cannot stat 'tbb/build/lib_release/tbb*.dll': No such file or directory
make: *** [Makevars:89: tbb] Error 1
ERROR: compilation failed for package 'RcppParallel'
* removing 'C:/R/Library/RcppParallel'
* restoring previous 'C:/R/Library/RcppParallel'

The downloaded source packages are in
        ‘C:\Users\hans_vancalster\AppData\Local\Temp\Rtmp4o9TSI\downloaded_packages’
Warning message:
In install.packages("RcppParallel", type = "source") :
  installation of package ‘RcppParallel’ had non-zero exit status
````

Installing the binary seems to work:
````
tall.packages("RcppParallel")
Installing package into ‘C:/R/Library’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://inla.r-inla-download.org/R/stable/bin/windows/contrib/4.0:
  cannot open URL 'https://inla.r-inla-download.org/R/stable/bin/windows/contrib/4.0/PACKAGES'
trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/RcppParallel_5.0.2.zip'
Content type 'application/zip' length 5167790 bytes (4.9 MB)
downloaded 4.9 MB

package ‘RcppParallel’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\hans_vancalster\AppData\Local\Temp\Rtmp4o9TSI\downloaded_packages
````

but when I do
````
library(RcppParallel)
> devtools::session_info()
- Session info ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       Windows 7 x64 SP 1          
 system   x86_64, mingw32             
 ui       Rgui                        
 language (EN)                        
 collate  Dutch_Belgium.1252          
 ctype    Dutch_Belgium.1252          
 tz       Europe/Paris                
 date     2020-07-16                  

- Packages --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 ! package      * version date       lib source        
   assertthat     0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
   backports      1.1.7   2020-05-13 [1] CRAN (R 4.0.0)
   callr          3.4.3   2020-03-28 [1] CRAN (R 4.0.0)
   cli            2.0.2   2020-02-28 [1] CRAN (R 4.0.0)
   crayon         1.3.4   2017-09-16 [1] CRAN (R 4.0.0)
   desc           1.2.0   2018-05-01 [1] CRAN (R 4.0.0)
   devtools       2.3.0   2020-04-10 [1] CRAN (R 4.0.2)
   digest         0.6.25  2020-02-23 [1] CRAN (R 4.0.0)
   ellipsis       0.3.1   2020-05-15 [1] CRAN (R 4.0.2)
   fansi          0.4.1   2020-01-08 [1] CRAN (R 4.0.0)
   fortunes       1.5-4   2016-12-29 [1] CRAN (R 4.0.0)
   fs             1.4.2   2020-06-30 [1] CRAN (R 4.0.2)
   git2r          0.27.1  2020-05-03 [1] CRAN (R 4.0.2)
   glue           1.4.1   2020-05-13 [1] CRAN (R 4.0.2)
   magrittr       1.5     2014-11-22 [1] CRAN (R 4.0.0)
   memoise        1.1.0   2017-04-21 [1] CRAN (R 4.0.0)
   pkgbuild       1.1.0   2020-07-13 [1] CRAN (R 4.0.0)
   pkgload        1.1.0   2020-05-29 [1] CRAN (R 4.0.2)
   prettyunits    1.1.1   2020-01-24 [1] CRAN (R 4.0.0)
   processx       3.4.3   2020-07-05 [1] CRAN (R 4.0.2)
   ps             1.3.3   2020-05-08 [1] CRAN (R 4.0.2)
   R6             2.4.1   2019-11-12 [1] CRAN (R 4.0.0)
 D RcppParallel * 5.0.2   2020-06-24 [1] CRAN (R 4.0.2)
   remotes        2.1.1   2020-02-15 [1] CRAN (R 4.0.0)
   rlang          0.4.6   2020-05-02 [1] CRAN (R 4.0.2)
   rprojroot      1.3-2   2018-01-03 [1] CRAN (R 4.0.0)
   sessioninfo    1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
   testthat       2.3.2   2020-03-02 [1] CRAN (R 4.0.0)
   usethis        1.6.1   2020-04-29 [1] CRAN (R 4.0.0)
   withr          2.2.0   2020-04-20 [1] CRAN (R 4.0.0)

[1] C:/R/Library
[2] C:/Program Files/R/R-4.0.2/library

 D -- DLL MD5 mismatch, broken installation.
> 
````

It indicates ` D -- DLL MD5 mismatch, broken installation.` for the RcppPackage so something seems to be wrong?

**Comment by eddelbuettel** [comment] 2020-07-16 19:11
Did you notice

> Warning: unable to access index for repository https://inla.r-inla-download.org/R/stable/bin/windows/contrib/4.0:
>  cannot open URL 'https://inla.r-inla-download.org/R/stable/bin/windows/contrib/4.0/PACKAGES'

I guess you could fetch the Windows package "manually" and point to it with `install.packages(file, repos=NULL)` where file is the path to the downloaded zip file.

**Comment by kevinushey** [comment] 2020-07-16 19:35
Also worth saying that your issue appears to be different:

> g++.exe: error: unrecognized command line option '-flifetime-dse=1'

as that particular error wasn't reported by the OP in this thread.

Still though, that flag should be supported by the latest version of Rtools. Have you installs Rtools 4.0? https://cran.r-project.org/bin/windows/Rtools/

**Comment by hansvancalster** [comment] 2020-07-17 07:07
@eddelbuettel That is because in my `Profile.site` I have:
````
repos = c(
    RStudio = "https://cloud.r-project.org/",
    INLA = "https://inla.r-inla-download.org/R/stable"
  )
````
the INLA repository is not yet available for R 4.x, but downloading from https://cloud.r-project.org/ went fine, so that warning should not be an issue.

@kevinushey you are right, the issue is different from the OP (should I open a new issue?)
I have rtools40:
````
Sys.which("make")
                              make 
"C:\\rtools40\\usr\\bin\\make.exe" 
````

Any ideas what goes wrong here with installation from source? 
And (maybe unrelated?) why after installing the windows binary, `devtools::session_info` flags the RcppPackage as `D -- DLL MD5 mismatch, broken installation`. 
I upgraded to R 4.02 yesterday (from R 4.0.0), could that be a reason?

**Comment by kevinushey** [comment] 2020-07-17 16:47
I think it's worth opening a new issue -- just in case other users on Windows bump into this as well. I don't know what's going on or how to fix it off the top of my head though.

**Comment by cdriveraus** [comment] 2020-07-17 16:49
I tried again, using:
 install.packages("RcppParallel",INSTALL_opts = '--no-multiarch',type='source')
same problems.  I don't have problems building from source in general, but sure, perhaps it is something local. This is not important to me anymore, just providing the info.

**Comment by koheiw** [comment] 2021-04-14 22:56
I can install RcppParallel but cannot build my package on Windows on Gihub Action due to the same error. The same happens on my local Windows 10.

https://github.com/koheiw/proxyC/pull/13/checks?check_run_id=2347806073
```
"C:/rtools40/mingw32/bin/"g++  -std=gnu++11 -I"C:/R/include" -DNDEBUG -DARMA_DONT_PRINT_OPENMP_WARNING=1 -I'D:/a/_temp/Library/Rcpp/include' -I'D:/a/_temp/Library/RcppParallel/include' -I'D:/a/_temp/Library/RcppArmadillo/include'     -DRCPP_PARALLEL_USE_TBB=1 -DARMA_64BIT_WORD=1   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c RcppExports.cpp -o RcppExports.o
"C:/rtools40/mingw32/bin/"g++  -std=gnu++11 -I"C:/R/include" -DNDEBUG -DARMA_DONT_PRINT_OPENMP_WARNING=1 -I'D:/a/_temp/Library/Rcpp/include' -I'D:/a/_temp/Library/RcppParallel/include' -I'D:/a/_temp/Library/RcppArmadillo/include'     -DRCPP_PARALLEL_USE_TBB=1 -DARMA_64BIT_WORD=1   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c linear.cpp -o linear.o
"C:/rtools40/mingw32/bin/"g++  -std=gnu++11 -I"C:/R/include" -DNDEBUG -DARMA_DONT_PRINT_OPENMP_WARNING=1 -I'D:/a/_temp/Library/Rcpp/include' -I'D:/a/_temp/Library/RcppParallel/include' -I'D:/a/_temp/Library/RcppArmadillo/include'     -DRCPP_PARALLEL_USE_TBB=1 -DARMA_64BIT_WORD=1   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c pair.cpp -o pair.o
C:/rtools40/mingw32/bin/g++ -shared -s -static-libgcc -o proxyC.dll tmp.def RcppExports.o linear.o pair.o -LC:/R/bin/i386 -lRlapack -LC:/R/bin/i386 -lRblas -L"D:/a/_temp/Library/RcppParallel/lib/i386" -ltbb -ltbbmalloc -LC:/R/bin/i386 -lR
C:/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -ltbb
C:/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -ltbbmalloc
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'proxyC'
```

**Comment by kevinushey** [comment] 2021-04-14 23:19
Sorry for the trouble. This is a bug in the version of RcppParallel just released to CRAN; I'll try to get it fixed and re-submitted ASAP.

**Comment by koheiw** [comment] 2021-04-14 23:39
That would be great! Thank you for maintaining the amazing package.

**Comment by kevinushey** [comment] 2021-04-14 23:57
I appreciate your thanks -- despite how little has changed in RcppParallel over the years, it is surprisingly challenging to keep alive on CRAN.

**Comment by koheiw** [comment] 2021-04-15 01:04
I believe we can write useful packages for R thanks to RcppParallel. R is disappointingly slow slow without it. CRAN should better support mutithreading infrastructures (TBB and OMP).

**Comment by kevinushey** [comment] 2021-04-15 19:07
I believe these issues should be resolved in the latest release of RcppParallel -- please feel free to re-open or file a new issue if you're still having trouble.

**Closed by kevinushey** 2021-04-15 19:07 UTC
